### PR TITLE
Update postinstall.js

### PR DESCRIPTION
**Pull request by njevdjo**

### CODE REVIEW

**Comment by chuckfairy** [comment]
pretty sure it's just author? https://github.com/chuckfairy/node-webcam/blob/master/package.json#L23

**Comment by chuckfairy** [comment]
pretty sure it's just author? https://github.com/chuckfairy/node-webcam/blob/master/package.json#L23

**Comment by njevdjo** [comment]
After install **node-webcam** node_modules/package.json  contains
image

You can try to debug postainstall.js after install **node-webcam**.

**Comment by chuckfairy** [comment]
gotcha thanks

**Pull request merged**
